spring.datasource.url=jdbc:mysql://localhost:3306/oficina_mecanica?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=